default:
  image: tmaier/docker-compose:latest
  tags:
    - run-22

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build

build-all:
  stage: build
  script:
    - docker-compose build
    - docker-compose run --rm app npm run test
